// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Classroom struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Query struct {
}

type Schedule struct {
	ID        string     `json:"id"`
	Subject   *Subject   `json:"subject"`
	Classroom *Classroom `json:"classroom"`
	DayOfWeek string     `json:"dayOfWeek"`
	Period    int        `json:"period"`
}

type Subject struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Todos []*Todo `json:"todos"`
}

type Todo struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}
